### ISSUE TITLE
opening CSV files containing several JV curves

### ISSUE THREAD

**Issue by ej-jp** [carronr/grapa#2]
Dear Prof Carron,

Thank you for publishing and making available to the public this graphical interface to visualize this type of research data.

Your software is very useful to me for quick on-the-spot visualization of the JV curves I am recording at the moment. And I wouldn't be surprised if with some tuning, I could get some graphics for publication quality. Also, I am contemplating including it academically in the master's course I am recently teaching because the feature for analyzing EQE.

I am writing to you because I am having a very hard time implementing a snippet to make it easier for me to open in Grapa the files containing JV curves generated in the Ossila software.

I have attached some example JV files generated but I will briefly summarize the problem:

JV curves and metrics are saved in separate csv type files (comma separator). Let's ignore now completely the csv with the metrics because Grapa can regenerate them and let's focus on the problem of opening the JV curves.   

The file that stores the JV curves can store a single curve or several curves. It is common in my field to save both forward curve (from Isc to Voc) and backward JV curve (from Voc to Isc). In our substrates there are several (8) measurable pixels and we usually save all JVs of a substrate in a single file. Grapa seems to only be able to correctly open files containing a single curve. Also, the cell metrics determination will fail if the JV curve was saved as backward in voltage. Furthermore, the opened file is detected as "Curve" but is not detected as "Curve JV".

What I have implemented so far, is a very messy python script that converts the JV curve files coming from the Ossila software into as many separate files as there are curves inside that csv. Also, if it detects that the curve is backward, it sorts it to be forward (please, see the ossila2grapa.py.zip attachment)

My question is whether using curveMycurve.py and/or graphMydata.py files, the workflow could be smoother for using Grapa.

Another suggestion is that pip installs an older Grapa version than the one currently available for download on github. My workflow for using the most recent Grapa version is to install miniconda, create environment for Grapa, download Grapa from github, rename the folder to just "grapa", run in terminal in such folder: python GUI.py

Best regards,
Emilio

  

[celda-silicio-JV-para-grapa.zip](https://github.com/carronr/grapa/files/10932581/celda-silicio-JV-para-grapa.zip)
[ossila2grapa.py.zip](https://github.com/carronr/grapa/files/10932582/ossila2grapa.py.zip)

**Comment by carronr** [comment]
Dear Emilio,

Thanks for your message and letting me know that you are using grapa, it's appreciated!

Grapa allows you to write your own procedures to open the file types you must deal with, without modifying existing code.
To help you I wrote a piece of code which should be able to open the files you provided me, including data series order (data order gets modified) and conversion from A/cm2 into mA/cm2.
Please simply copy the file https://github.com/carronr/grapa/tree/master/datatypes/graphJVOssila.py into your folder grapa/datatypes, and restart grapa, hopefully it will work.

I am not clear what you want me to do with the last suggestion. Maybe you can recover earlier versions of grapa from the github repository, even if I would not recommend it.

To start grapa, you can just execute the file GUI.py. Actually I usually start it by executing a .bat launcher (windows environment), which content could be:
> python C:\myfolder\somesubfolder\grapa\GUI.py"
> pause

Best regards,
Romain

**Comment by ej-jp** [comment]
Dear Romain,
Thank you very much! it works perfect. Grapa is truly awesome!

Regarding my last suggestion, I'm sorry, I didn't explain it well. According to the READ.ME file, the recommended way to install and run GRAPA is to use "pip install" and then from the python console do import grapa... etc.

This works, but "pip" will install an older version of GRAPA (0.548 or so). And actually the tabs feature is very useful and this old version doesn't have it. I also found it cumbersome to have to open the python terminal to do "import" etc. Also, the "Annotations, legend and titles" button doesn't work in that old version (no problem in 0.6, everything perfect).

Then, my last suggestion was about to update the READ.ME file with this install/run procedure. But I didn't explain it well in my first comment.


I will follow your recommendation preparing a bat file for windows. In my linux machine Grapa runs ok calling GUI.py using the specific python binary in the corresponding conda environment.

Thank you again!




I have another suggestion but please there is no hurry to implement it.


This is about integrating the short circuit current from the EQE charts. I see that GRAPA can get the numerical value of this parameter but eventually it is necessary to see the graph of the integration superimposed on the EQ graph.


I have a code in matlab to draw this curve if it is of help and I can send you.

**Comment by carronr** [comment]
Dear Emilio,
Thanks for your positive feedback!

That's correct, I did not recently transfer the current version to the pypi repo to make it available through pip. I'll do that in coming days, also restructure the repo more standard form.

Indeed EQE current integration no show the integrated current curve. It should not be a problem to add it.

Best regards,
Romain

**Comment by carronr** [comment]
Version 0.6.1.0 is now out, on github and also can be downloaded directly using `pip install grapa`.

Amongst the changes, the additional functionality for EQE curve was added.
