### ISSUE TITLE
Appearance -Dark

### ISSUE THREAD

**Issue by jeronimo9505** [carronr/grapa#3]
Hello dear,

I have activated the Appearance Dark when I executive GUI.py open with a dark appearance.
This looks nice, however, it is not possible to properly display some parts of the interface.

is it possible to change the appearance without changing my configuration system?

![image](https://github.com/carronr/grapa/assets/162699334/8077391f-f1f5-4635-bd15-318ef31f8726)

**Comment by carronr** [comment]
Dear jeronimo9505
Thanks for your interest!
I updated the code with stuff waiting, and also tried something to help with your dark mode. I spotted issues in the property Tree with text displayed dark-on-dark. Maybe I missed other problematic areas?
Could you please try and report?
In case not successful, could you please indicate how you did set up the dark mode, so I can try by myself?

**Comment by jeronimo9505** [comment]
Dear carronr 

Thanks for taking your time , it is very useful. 

I downloaded your last version of code and I execute GUI.py by macOS terminal, however,  The problem was fixed, however other parts that have similar problems are:

-Screen dpi (white letter with whit background)
-Symbol  * left button * zoom
***Look screenshot 

In other hand, I would like to know if it is posible to plot with dot line, I couldn't find this option.

Again, thanks for taking your time 


![Screenshot 2024-04-22 at 16 04 14](https://github.com/carronr/grapa/assets/162699334/b1ed0199-4e3e-45d7-a0c7-405aa626c55d)

**Comment by carronr** [comment]
It's a bit of a guesswork as I cannot test myself. I updated the github code. Could you please download and try again?
- Tree black-on-black: modified, hopefully it still works?
- Screen dpi Entry: please check?
- Toolbar: unfortunately, outside of my scope. Depending on your python distribution I import NavigationToolbar2TkAgg or NavigationToolbar2Tk from matplotlib.backends.backend_tkagg. Maybe they are aware of the issue.
- Dotted line: could you try to select a Curve, property "linespec", and enter ".-", "-.", or "--" ?
I tried to keep the keywords and values as close as possible to the underlying matplotlib library.

**Comment by jeronimo9505** [comment]
Dear carronr, 

All the problem was fixed. 
Thanks for taking your time
