### ISSUE TITLE
Export data - Terminal/Console 

### ISSUE THREAD

**Issue by jeronimo9505** [carronr/grapa#4]
Dear Carrornr

First, I would like to say that your program is really useful, I use it mainly for JV curves and get information of Voc, Jsc, FF, EFF and MPP. 

I started to get a lot of curves per device, so this could take a long time to process all the information.

My question is, could be possible to export all the data that print on the terminal like .txt or . CSV, can help me to get all the information (Voc, Jsc, FF, EFF and MPP)? and then I can process this information and compare it between devices.

Now I have to copy and paste every  information of the curve (for every device I have 4 curves, and normally I have 7 or 10 devices, so in total are around 28-40 curves) and this takes me a long time.  

I appreciate your time and thank you for your help. 

Best Regards 

![Screenshot 2024-04-29 at 13 15 36](https://github.com/carronr/grapa/assets/162699334/23dc2c1d-aecf-4d6d-aaf2-7a4bbaa87389)

**Comment by carronr** [comment]
Dear jeronimo9505,

Thank you for your feedback!

You can open the IV curves into a single grapa graph (as shown on the screenshot), save the graph, then open the .txt file using e.g. notepad or excel. Look at the lines of interest, starting with "voc", "ff", "jsc" and "eff".

Alternatively, if you wish additional data or cell area correction, could you try, left menu, script, "Fit curves separately" ?
The script should try to fit the curves with 1-diode model with 2 resistor, and finally create different files including a summary file including PV parameters. There is an feature for automatic area correction (e.g. a file named "area.txt" in same folder), but pixel identification relies on specific naming conventions and I don't know if this can be readily applied in your case.

**Comment by jeronimo9505** [comment]
Dear Carronr 

Thanks for your help,
Yes, I found all the information in the file .txt with all my data (more than 8 jv curves), and then I did a script in Excel to take just the information that I needed, now this is easier. 

Thanks for your time!
